# Generated by Django 5.0.7 on 2024-07-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_alter_seat_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showtime',
            name='price_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='price_kids',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='price_seniors',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
