# Generated by Django 5.0.7 on 2024-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_civil_status_alter_userprofile_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
