# Generated by Django 5.0.7 on 2024-07-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'General'), ('kids', 'Kids'), ('seniors', 'Seniors')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
