# Generated by Django 5.0.7 on 2024-07-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('kids', 'Kids'), ('seniors', 'Seniors')], max_length=10, null=True),
        ),
    ]
