# Generated by Django 5.0.7 on 2024-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
